export const categorys = [
    { description: '', value: '치킨' },
    { description: '', value: '한식' },
    { description: '', value: '카페/디저트' },
    { description: '', value: '중식' },
    { description: '', value: '분식' },
    { description: '', value: '샌드위치' },
    { description: '', value: '일식' },
    { description: '', value: '양식' },
    { description: '', value: '아시안' },
    { description: '', value: '고기' },
    { description: '', value: '찜/탕' },
    { description: '', value: '족발/보쌈' },
    { description: '', value: '야식' },
    { description: '', value: '도시락' },
 ]